name: chatty
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.13.0'

dependencies:
  flutter:
    sdk: flutter

  # Remove the following line, as flutter_cupertino_localizations is no longer needed
  # flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^1.0.5

  # GetX
  get: ^4.6.5

  intl: ^0.18.1

  flutter_screenutil: ^5.8.4

  pull_to_refresh: ^2.0.0

  fluttertoast: ^8.2.2

  flutter_easyloading: ^3.0.5

  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.8

  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1

  crypto: ^3.0.3

  webview_flutter: ^4.2.2

  loading_animations: ^2.2.0

  share_plus: ^7.1.0
  device_info_plus: ^9.0.3

  package_info_plus: ^4.1.0

  path_provider: ^2.1.0

  permission_handler: ^10.4.3

  sentry: ^7.9.0

  uni_links: ^0.5.1

  flutter_spinkit: ^5.2.0

  dots_indicator: ^3.0.0

  google_sign_in: ^6.1.4

  firebase_core: ^2.15.1

  firebase_messaging: ^14.6.6

  firebase_in_app_messaging: ^0.7.3+5

  firebase_auth: ^4.7.3

  cloud_firestore: ^4.8.5

  firebase_storage: ^11.2.6

  location: ^5.0.3

  image_picker: ^1.0.2

  photo_view: ^0.14.0

  sqflite: ^2.3.0

  flutter_verification_code: ^1.1.6

  agora_rtc_engine: ^6.2.2

  just_audio: ^0.9.34

  flutter_local_notifications: ^15.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/Sound_Horizon.mp3
    - assets/audio_mixing/Agora.io-Interactions.mp3
    - assets/agora-logo.png
    - assets/dang.mp3
    - assets/ding.mp3
    - assets/gif.gif
    - assets/jpg.jpg

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
